### ISSUE TITLE
SMS Reader not working for latest expo cli

### ISSUE THREAD

**Issue by manojkumar3692** [maniac-tech/ExpoReadSMS-TestApp#5]
I got this message when i tried to run the app 
```
This version of expo-cli is not supported anymore.          
 It's highly recommended to update to the newest version. 
│The API endpoints used in this version of expo-cli might not exist,     │
any interaction with Expo servers may result in unexpected behaviour.
```

and when i tried to install this with latest cli , it was not working

**Comment by maniac-tech** [comment]
Will look into this @manojkumar3692 

Please share the steps you followed, in order to make easier and faster for me to repro and fix it too.

**Comment by maniac-tech** [comment]
Any updates here @manojkumar3692 ?

**Comment by maniac-tech** [comment]
Will close this by EOD today, if no further updates are shared.
